// Recipe edit history. You tweak a recipe over a year — more garlic, less time — and eventually
// want the version from before you ruined it. Every save keeps a snapshot of what it looked like
// *before* the edit, capped so the kv row cannot grow without bound.
import type { Recipe } from './types';

export const MAX_REVISIONS = 12;

export interface Revision {
  at: number;
  /** Short description of what changed, generated by diffing. */
  summary: string;
  /** The full recipe as it was before this edit. */
  snapshot: Recipe;
}

export type HistoryMap = Record<string, Revision[]>;

export function parseHistory(value: unknown): HistoryMap {
  if (!value || typeof value !== 'object') return {};
  const out: HistoryMap = {};
  for (const [id, raw] of Object.entries(value as Record<string, unknown>)) {
    if (!Array.isArray(raw)) continue;
    const revs: Revision[] = [];
    for (const r of raw) {
      const rr = r as Partial<Revision>;
      if (typeof rr?.at !== 'number' || !rr.snapshot || typeof rr.snapshot !== 'object') continue;
      revs.push({ at: rr.at, summary: typeof rr.summary === 'string' ? rr.summary : 'Edited', snapshot: rr.snapshot as Recipe });
    }
    if (revs.length) out[id] = revs.sort((a, b) => b.at - a.at).slice(0, MAX_REVISIONS);
  }
  return out;
}

/** Human summary of what an edit did, for the history list. */
export function diffSummary(before: Recipe, after: Recipe): string {
  const bits: string[] = [];
  if (before.title !== after.title) bits.push('renamed');
  if (before.baseServings !== after.baseServings) bits.push(`servings ${before.baseServings} → ${after.baseServings}`);
  if (before.prepMin + before.cookMin !== after.prepMin + after.cookMin) bits.push('timing');

  const beforeIng = new Map(before.ingredients.map((i) => [i.ingredientId, i]));
  const afterIng = new Map(after.ingredients.map((i) => [i.ingredientId, i]));
  let added = 0;
  let removed = 0;
  let changed = 0;
  for (const [id, a] of afterIng) {
    const b = beforeIng.get(id);
    if (!b) added += 1;
    else if (b.qty !== a.qty || b.unit !== a.unit) changed += 1;
  }
  for (const id of beforeIng.keys()) if (!afterIng.has(id)) removed += 1;
  if (added) bits.push(`+${added} ingredient${added === 1 ? '' : 's'}`);
  if (removed) bits.push(`−${removed} ingredient${removed === 1 ? '' : 's'}`);
  if (changed) bits.push(`${changed} amount${changed === 1 ? '' : 's'} changed`);

  if (before.steps.length !== after.steps.length) bits.push('steps');
  else if (before.steps.some((s, i) => s !== after.steps[i])) bits.push('step wording');
  if ((before.notes ?? '') !== (after.notes ?? '')) bits.push('notes');

  return bits.length ? bits.join(', ') : 'Edited';
}

/** Push a pre-edit snapshot onto the stack, newest first, trimmed. */
export function pushRevision(history: HistoryMap, before: Recipe, after: Recipe, at: number): HistoryMap {
  const rev: Revision = { at, summary: diffSummary(before, after), snapshot: before };
  const existing = history[before.id] ?? [];
  return { ...history, [before.id]: [rev, ...existing].slice(0, MAX_REVISIONS) };
}

/** Drop a recipe's history entirely (used when a recipe is deleted). */
export function forgetHistory(history: HistoryMap, recipeId: string): HistoryMap {
  if (!history[recipeId]) return history;
  const next = { ...history };
  delete next[recipeId];
  return next;
}
